### ISSUE TITLE
IE Petroleum + TFC-IE-Crossover

### ISSUE THREAD

**Issue by exelent352** [NMagpie/TFC-IE-Crossover#14]
I ran into a problem in the assembly of TFC+TFCIECrossover+IEPetroleum, that because of TFCIECrossover, crafting in Coker stops working
![image](https://github.com/NMagpie/TFC-IE-Crossover/assets/84282979/9e878709-1069-4119-8682-845210921715)
![image](https://github.com/NMagpie/TFC-IE-Crossover/assets/84282979/ae80f736-c8f9-43c7-9b1b-db54f6b4ba9c)

**Comment by HermitOwO** [comment]
fixed in [5793d13](https://github.com/NMagpie/TFC-IE-Crossover/commit/5793d13572055d3aebb5e7b23fde3fae85e0e8dd)
