### ISSUE TITLE
[Suggestion] treated wood manufacturing in barrels

### ISSUE THREAD

**Issue by lordi-erez** [NMagpie/TFC-IE-Crossover#7]
many recipes still need treated wood, and rn it requires a vanilla bucket of creosote

for example: windmill blades

or at the very least make it create firmalife treated lumber, and make it recipe-usable

**Comment by HermitOwO** [comment]
That's incorrect. JEI shows that it requires a vanilla bucket but in fact you can craft with a wooden bucket.

**Comment by lordi-erez** [comment]
also do IE crates follow size limits?

**Comment by HermitOwO** [comment]
Currently they don't.
